### ISSUE TITLE
Adding a quick start / installation process

### ISSUE THREAD

**Issue by mvy** [Mesona/ars_tools#18]
Hi, 

I think it would be really useful to get a quick installation guide. I am not very familiar with ruby, and having at least some hint on where to look for would certainly be great help.

Thanks!

**Comment by Mesona** [comment]
Oh wow, yeah, I'll definitely get that to you today and add it to the git
repo as well!

**Comment by Mesona** [comment]
I've updated with the installation steps. I think that's everything, but please let me know if you run into any issues

**Comment by mvy** [comment]
I'll have a go at it, might try to spin a docker instance for that. Thanks!
